import React, { useState, useEffect } from 'react';

function MilestonesView({ apiBase }) {
  const [milestones, setMilestones] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openWeekId, setOpenWeekId] = useState(null);

  useEffect(() => {
    fetchMilestones();
  }, []);

  const fetchMilestones = async () => {
    try {
      const res = await fetch(`${apiBase}/milestones`);
      const data = await res.json();
      setMilestones(data);
      if (data.length > 0) {
        setOpenWeekId(data[0].id);
      }
    } catch (err) {
      console.error("Error fetching milestones:", err);
    } finally {
      setLoading(false);
    }
  };

  const toggleAccordion = (id) => {
    if (openWeekId === id) {
      setOpenWeekId(null);
    } else {
      setOpenWeekId(id);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '60vh', alignItems: 'center', justifyContent: 'center' }}>
        <div className="stream-spinner"></div>
      </div>
    );
  }

  return (
    <div className="glass-card" style={{ padding: '2rem' }}>
      <div style={{ marginBottom: '2rem' }}>
        <h2 style={{ fontSize: '1.5rem' }}>Goal Milestones</h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>Weekly roadmaps generated by the Planner Agent. Track performance week-by-week.</p>
      </div>

      {milestones.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-muted)' }}>
          <h3>No milestones generated yet. Set an active goal.</h3>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {milestones.map((m) => {
            const isOpen = openWeekId === m.id;
            return (
              <div key={m.id} className="milestone-accordion">
                <div 
                  className={`milestone-header ${isOpen ? 'open' : ''}`}
                  onClick={() => toggleAccordion(m.id)}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <div className="brand-icon" style={{ width: '28px', height: '28px', fontSize: '0.9rem' }}>
                      {m.week_number}
                    </div>
                    <div>
                      <h4 style={{ fontSize: '1.1rem', color: 'var(--text-main)' }}>{m.title}</h4>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                        Target hours: {m.estimated_hours} hrs
                      </span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.2rem' }}>
                      <span style={{ fontSize: '0.8rem', fontWeight: '600', color: m.completion_rate === 100 ? 'var(--color-success)' : 'var(--text-main)' }}>
                        {m.completion_rate}% Complete
                      </span>
                      <div className="milestone-progress-bar-container">
                        <div 
                          className="milestone-progress-bar"
                          style={{ 
                            width: `${m.completion_rate}%`,
                            background: m.completion_rate === 100 ? 'var(--color-success)' : 'linear-gradient(90deg, var(--color-primary), var(--color-secondary))' 
                          }}
                        ></div>
                      </div>
                    </div>
                    <span style={{ fontSize: '1.2rem', transform: isOpen ? 'rotate(180deg)' : 'none', transition: 'var(--transition-smooth)' }}>
                      ▼
                    </span>
                  </div>
                </div>

                {isOpen && (
                  <div className="milestone-body">
                    {/* Milestone Objective */}
                    <div style={{ marginBottom: '1.5rem' }}>
                      <h5 style={{ fontSize: '0.95rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '0.5rem', letterSpacing: '0.05em' }}>
                        Weekly Objective
                      </h5>
                      <p style={{ fontSize: '1rem', lineHeight: '1.5' }}>
                        {m.objective}
                      </p>
                    </div>

                    {/* Resources & Dependencies row */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
                      {/* Learning Resources */}
                      <div>
                        <h5 style={{ fontSize: '0.95rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '0.5rem', letterSpacing: '0.05em' }}>
                          Learning Resources
                        </h5>
                        {m.learning_resources.length === 0 ? (
                          <p style={{ fontStyle: 'italic', fontSize: '0.9rem', color: 'var(--text-dim)' }}>No learning resources specified.</p>
                        ) : (
                          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
                            {m.learning_resources.map((res, idx) => (
                              <li key={idx} style={{ fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                <span style={{ color: 'var(--color-secondary)' }}>🔗</span>
                                <span>{res}</span>
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>

                      {/* Dependencies */}
                      <div>
                        <h5 style={{ fontSize: '0.95rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '0.5rem', letterSpacing: '0.05em' }}>
                          Dependencies
                        </h5>
                        {m.dependencies.length === 0 ? (
                          <p style={{ fontStyle: 'italic', fontSize: '0.9rem', color: 'var(--text-dim)' }}>None. This week stands alone.</p>
                        ) : (
                          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
                            {m.dependencies.map((dep, idx) => (
                              <li key={idx} style={{ fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                <span style={{ color: 'var(--color-warning)' }}>⚠️</span>
                                <span>{dep}</span>
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default MilestonesView;
